apiVersion: v1
kind: Service
metadata:
  name: pihole-lb
  namespace: home
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole-dns"
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53